wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/wallpaper/wallhaven-lydkg2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/wallpaper/wallhaven-lydkg2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/fallback.jxl
    fit_mode = cover
}
